version: "3"

services:
  db:
    environment:
      - POSTGRES_PASSWORD=hanusovedni
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata:delegated
      - .:/code:delegated
    ports:
      - "5432:5432"

  web:
    ports:
      - "8000:8000"
    volumes:
      - .:/code:delegated
      - /Users/jozo/d/bhd/assets:/bhd_images:delegated
      - /Users/jozo/d/bhd/wp-content/themes/bhd/assets/img/illustrations:/bhd_illustrations:delegated
    command: ./manage.py runserver 0:8000

  nginx:
    volumes:
      - ./static:/usr/share/nginx/static:delegated
      - ./media:/usr/share/nginx/media:delegated

  reverse-proxy:
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:delegated
