services:
  db:
    environment:
      - POSTGRES_PASSWORD=hanusovedni
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data/pgdata
      - .:/code
    ports:
      - "5432:5432"

  web:
    build: .
    #image: hn1
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0:8000
    volumes:
      - ./src:/code:delegated
      - ./docker/static:/static_root
      - ./docker/media:/media_root

  caddy:
    ports:
      - "80:80"
      - "443:443"
      - "8080:80"
    volumes:
      - ./docker/static:/var/www/static/
      - ./docker/media:/var/www/media/

networks:
  hanusnet:
    driver: overlay
    attachable: true
