version: "3"

services:
  db:
    environment:
      - POSTGRES_PASSWORD=hanusovedni
    ports:
    - "5432:5432"

  web:
    volumes:
      - .:/code:delegated
    ports:
      - 9191:9191
    environment:
      - DJANGO_ENV=dev
    command: ./manage.py runserver 0:8000
#    command: uwsgi --http 0.0.0.0:8000 --chdir /code/ --wsgi-file hanusovedni/wsgi.py --master --processes 2 --threads 2 --stats 0.0.0.0:9191 --static-map /static=/code/static --static-map /media=/code/media
