version: "3.8"

services:
  db:
    environment:
      - POSTGRES_PASSWORD=hanusovedni
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  web:
    build: .
    #image: hn1
    command: ./manage.py runserver 0:8000
    volumes:
      - ./src:/code:delegated
      - ./docker/static:/static_root
      - ./docker/media:/media_root

  caddy:
    image: caddy
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./docker/static:/var/www/static/
      - ./docker/media:/var/www/media/
    networks:
      - hanusnet
