debug: True
log:
  level: DEBUG

accessLog: {}
ping: true

entryPoints:
  web-entry:
    address: :80
  web-entry-secure:
    address: :443


api:
  insecure: true
  dashboard: true
  debug: true


providers:
  docker:
    exposedByDefault: false
