# Generated by Django 2.2.9 on 2020-02-08 09:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_festivalpage_formatted_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festivalpage",
            name="formatted_title",
            field=wagtail.fields.RichTextField(default="", verbose_name="titulok"),
        ),
    ]
