# Generated by Django 2.2.9 on 2020-02-08 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_auto_20200208_1045"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HeaderSettings",
        ),
    ]
