# Generated by Django 2.2.9 on 2020-02-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_delete_headersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="title",
            field=models.CharField(default="", max_length=255, verbose_name="názov"),
        ),
    ]
