# Generated by Django 2.2.9 on 2020-02-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200208_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'rečník', 'verbose_name_plural': 'rečníci'},
        ),
    ]
