# Generated by Django 2.2.9 on 2020-02-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_remove_heroimage_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoinvite",
            name="name",
        ),
    ]
