# Generated by Django 2.2.9 on 2020-02-24 16:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_remove_videoinvite_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalpage",
            name="partners2",
            field=wagtail.core.fields.StreamField(
                [
                    ("heading", wagtail.core.blocks.CharBlock(classname="full title")),
                    ("url", wagtail.core.blocks.URLBlock()),
                    ("logo", wagtail.images.blocks.ImageChooserBlock()),
                ],
                blank=True,
            ),
        ),
    ]
