# Generated by Django 2.2.9 on 2020-02-24 16:05

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_festivalpage_partners2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festivalpage",
            name="partners2",
            field=wagtail.core.fields.StreamField(
                [
                    ("heading", wagtail.core.blocks.CharBlock(classname="title")),
                    (
                        "partner",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("url", wagtail.core.blocks.URLBlock()),
                                ("logo", wagtail.images.blocks.ImageChooserBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
