# Generated by Django 2.2.9 on 2020-02-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0021_speaker_speaker_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speaker",
            name="speaker_id",
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
