# Generated by Django 2.2.9 on 2020-02-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0022_auto_20200227_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_id",
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
