# Generated by Django 3.0.3 on 2020-03-07 12:27

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("home", "0027_supportpage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnersPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "partner",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "logo",
                                            wagtail.images.blocks.ImageChooserBlock(),
                                        ),
                                        ("body", wagtail.blocks.RichTextBlock()),
                                    ]
                                ),
                            )
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name": "partneri",
            },
            bases=("wagtailcore.page",),
        ),
    ]
