# Generated by Django 3.0.3 on 2020-03-07 14:37

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_auto_20200307_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalpage",
            name="headline",
            field=wagtail.fields.StreamField(
                [
                    (
                        "headliner",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock()),
                                ("photo", wagtail.images.blocks.ImageChooserBlock()),
                                ("link", wagtail.blocks.PageChooserBlock()),
                                ("description", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                null=True,
            ),
        ),
    ]
