# Generated by Django 3.0.3 on 2020-03-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_auto_20200314_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="wordpress_id",
            field=models.IntegerField(default=0),
        ),
    ]
