# Generated by Django 3.0.4 on 2020-03-21 16:31

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_crowdfundingpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalpage",
            name="hero_buttons",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_buttons",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.URLBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Len prvé 2 tlacidla budú použité",
                null=True,
            ),
        ),
    ]
