# Generated by Django 3.0.4 on 2020-03-21 16:58

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0041_festivalpage_hero_buttons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festivalpage",
            name="hero_buttons",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "hero_buttons",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("title", wagtail.core.blocks.CharBlock()),
                                ("link", wagtail.core.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Len prvé 2 tlacidla budú použité",
                null=True,
            ),
        ),
    ]
