# Generated by Django 3.0.4 on 2020-04-07 18:33

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0044_auto_20200407_1830"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalpage",
            name="formatted_title_en",
            field=wagtail.fields.RichTextField(default="", verbose_name="titulok"),
        ),
        migrations.AddField(
            model_name="festivalpage",
            name="headline_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "headliner",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock()),
                                ("photo", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "link",
                                    wagtail.blocks.PageChooserBlock(
                                        page_type=["home.Speaker"]
                                    ),
                                ),
                                ("description", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="festivalpage",
            name="hero_buttons_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_buttons",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Len prvé 2 tlacidla budú použité",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="festivalpage",
            name="hero_text_en",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="festivalpage",
            name="video_text_en",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
