# Generated by Django 3.0.4 on 2020-04-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0048_auto_20200409_2129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="title_sk",
            field=models.CharField(max_length=32),
        ),
    ]
