# Generated by Django 3.0.4 on 2020-04-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0053_translationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Titulok stránky ktorý budú vidieť ostatní návštevníci",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
    ]
