# Generated by Django 3.0.4 on 2020-04-18 18:46

import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0056_festivalpage_partners2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="festivalpage",
            name="partners2",
            field=wagtail.core.fields.StreamField(
                [
                    ("heading", wagtail.core.blocks.CharBlock(classname="title")),
                    (
                        "partner",
                        wagtail.core.blocks.StructBlock(
                            [
                                ("logo", wagtail.images.blocks.ImageChooserBlock()),
                                ("url", wagtail.core.blocks.URLBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
    ]
