# Generated by Django 3.0.4 on 2020-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_partner2_partnersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnersection',
            name='title_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='partnersection',
            name='title_sk',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
