# Generated by Django 3.0.4 on 2020-04-19 08:41

import wagtail.blocks
import wagtail.fields
from django.db import migrations

import home.models.data_models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0060_auto_20200419_0833"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalpage",
            name="partner_sections",
            field=wagtail.fields.StreamField(
                [
                    (
                        "partner_section",
                        wagtail.blocks.StructBlock(
                            [
                                ("title_sk", wagtail.blocks.CharBlock()),
                                ("title_en", wagtail.blocks.CharBlock()),
                                (
                                    "partners",
                                    wagtail.blocks.ListBlock(
                                        home.models.data_models.PartnerBlock
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
            ),
        ),
    ]
