# Generated by Django 3.0.4 on 2020-04-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_festivalpage_partner_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festivalpage',
            name='partners2',
        ),
    ]
