# Generated by Django 3.0.4 on 2020-04-19 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0062_remove_festivalpage_partners2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="partner",
            name="page",
        ),
        migrations.DeleteModel(
            name="MediaPartner",
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
    ]
