# Generated by Django 3.0.4 on 2020-04-21 09:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0064_streampage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streampage",
            name="body_en",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="streampage",
            name="body_sk",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
