# Generated by Django 3.0.4 on 2020-04-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0067_auto_20200421_0948"),
    ]

    operations = [
        migrations.AddField(
            model_name="streampage",
            name="google_form_url",
            field=models.URLField(blank=True),
        ),
    ]
