# Generated by Django 3.0.4 on 2020-04-22 17:34

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0068_streampage_google_form_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="moderators",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="events_as_moderator", to="home.Speaker"
            ),
        ),
    ]
