# Generated by Django 3.0.4 on 2020-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0069_event_moderators"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
