# Generated by Django 3.0.4 on 2020-04-22 23:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0071_auto_20200422_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderatorconnection",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderator_connections",
                to="home.Event",
            ),
        ),
    ]
