# Generated by Django 3.0.4 on 2020-04-22 23:25

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0071_auto_20200422_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderatorconnection",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderator_connections",
                to="home.Event",
            ),
        ),
    ]
