# Generated by Django 3.0.4 on 2020-04-22 23:38

from django.db import migrations


def forward(apps, schema_editor):
    Event = apps.get_model("home", "Event")
    SpeakerConnection = apps.get_model("home", "SpeakerConnection")

    for event in Event.objects.iterator():
        for speaker in event.speakers.all():
            event.speaker_connections.add(
                SpeakerConnection.objects.create(speaker=speaker, event=event)
            )


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0073_auto_20200422_2332"),
    ]

    operations = [migrations.RunPython(forward, backward)]
