# Generated by Django 3.0.4 on 2020-04-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0074_auto_20200422_2338"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="speakers",),
    ]
