# Generated by Django 3.0.4 on 2020-04-24 01:24

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("home", "0076_auto_20200424_0108"),
    ]

    operations = [
        migrations.AddField(
            model_name="streampage",
            name="background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtailimages.Image",
            ),
        ),
        migrations.AlterField(
            model_name="festivalpage",
            name="hero_buttons_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_buttons",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Len prvé 3 tlacidla budú použité",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="festivalpage",
            name="hero_buttons_sk",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_buttons",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                ("link", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="Len prvé 3 tlacidla budú použité",
                null=True,
            ),
        ),
    ]
