# Generated by Django 3.0.4 on 2020-04-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0077_auto_20200424_0124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streampage",
            name="stream_url",
            field=models.URLField(blank=True),
        ),
    ]
