# Generated by Django 3.0.4 on 2020-04-26 18:44

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0045_assign_unlock_grouppagepermission"),
        ("wagtailimages", "0001_squashed_0021"),
        ("home", "0080_auto_20200426_1836"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "event", "verbose_name_plural": "events"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={},
        ),
        migrations.AlterModelOptions(
            name="speaker",
            options={"verbose_name": "speaker", "verbose_name_plural": "speakers"},
        ),
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.Category",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.Location",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="related_festival",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="ticket_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Supports Youtube, Vimeo and <a href='https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/oembed_providers.py' target='_blank'>other websites</a>",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="url_to_map",
            field=models.URLField(
                help_text="URL to Google Maps or similar service",
                verbose_name="URL to map",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="description_sk",
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="first_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="last_name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
