# Generated by Django 3.0.4 on 2020-04-26 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0081_auto_20200426_1844"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "podujatie", "verbose_name_plural": "podujatia"},
        ),
        migrations.AlterModelOptions(
            name="programindexpage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="speaker",
            options={"verbose_name": "rečník", "verbose_name_plural": "rečníci"},
        ),
        migrations.AlterField(
            model_name="aboutfestivalpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="crowdfundingpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="donatepage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_and_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="dátum a čas"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Podporuje Youtube, Vimeo a <a href='https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/oembed_providers.py' target='_blank'>ďalšie stránky</a>",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventindexpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="festivalpage",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="koniec festivalu"
            ),
        ),
        migrations.AlterField(
            model_name="festivalpage",
            name="place",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="miesto"
            ),
        ),
        migrations.AlterField(
            model_name="festivalpage",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="začiatok festivalu"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="url_to_map",
            field=models.URLField(
                help_text="URL adresa na Google Mapy alebo obdobnú službu",
                verbose_name="URL k mape",
            ),
        ),
        migrations.AlterField(
            model_name="partnerspage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="programindexpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="speakerindexpage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
        migrations.AlterField(
            model_name="streampage",
            name="title_en",
            field=models.CharField(
                blank=True,
                help_text="Názov stránky, ako by ste chceli, aby sa zobrazoval verejnosti",
                max_length=255,
                verbose_name="titulok",
            ),
        ),
    ]
