# Generated by Django 3.0.4 on 2020-05-09 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0083_opengraphimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="related_festival",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="home.FestivalPage",
            ),
        ),
    ]
