# Generated by Django 3.1.1 on 2020-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_auto_20200920_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampage',
            name='slido_url',
            field=models.URLField(blank=True, verbose_name='Sli.do'),
        ),
    ]
