# Generated by Django 3.1.3 on 2020-11-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0097_auto_20201126_1756"),
    ]

    operations = [
        migrations.AddField(
            model_name="streampage",
            name="popup_donation_button_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
