# Generated by Django 3.1.7 on 2021-05-29 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0102_auto_20210525_1452"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrowdfundingCandlePage",
            fields=[
                (
                    "crowdfundingrocket2page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.crowdfundingrocket2page",
                    ),
                ),
            ],
            options={"verbose_name": "crowdfunding - candle",},
            bases=("home.crowdfundingrocket2page",),
        ),
    ]
