# Generated by Django 3.2.8 on 2021-10-10 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0108_mirrorpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
