# Generated by Django 3.2.8 on 2021-10-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0109_delete_menuitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitonTicketsPage",
            fields=[
                (
                    "genericpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="home.genericpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("home.genericpage",),
        ),
    ]
