# Generated by Django 4.1.7 on 2023-02-26 14:41

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0114_alter_aboutfestivalpage_body_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="festivalpage",
            name="video_invites_en",
            field=wagtail.fields.StreamField(
                [
                    (
                        "url",
                        wagtail.blocks.URLBlock(
                            help_text="Vlož sem link na YouTube alebo obdobné stránky"
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="festivalpage",
            name="video_invites_sk",
            field=wagtail.fields.StreamField(
                [
                    (
                        "url",
                        wagtail.blocks.URLBlock(
                            help_text="Vlož sem link na YouTube alebo obdobné stránky"
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.DeleteModel(
            name="VideoInvite",
        ),
    ]
