# Generated by Django 4.1.7 on 2023-02-26 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0116_alter_event_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="festivalpage",
            name="hero_text_en",
        ),
        migrations.RemoveField(
            model_name="festivalpage",
            name="hero_text_sk",
        ),
    ]
