# Generated by Django 4.1.7 on 2023-02-28 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0117_remove_festivalpage_hero_text_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactpage",
            name="right_image",
        ),
    ]
