# Generated by Django 2.1.8 on 2019-04-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190430_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='logo',
        ),
    ]
