# Generated by Django 2.1.8 on 2019-05-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190510_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
