# Generated by Django 2.2.9 on 2020-02-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0011_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
