# Generated by Django 2.1.8 on 2019-05-10 18:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190510_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersettings',
            name='title',
            field=wagtail.core.fields.RichTextField(default='Bratislavské Hanusove dni'),
        ),
    ]
