# Generated by Django 2.1.8 on 2019-06-16 09:22

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190616_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.Speaker'),
        ),
    ]
