# Generated by Django 2.2.9 on 2020-01-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0017_speakerindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('url_to_map', models.URLField(help_text='URL adresa na Google Mapy alebo obdobnú službu', verbose_name='URL k mape')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'podujatie', 'verbose_name_plural': 'podujatia'},
        ),
        migrations.AlterModelOptions(
            name='eventindexpage',
            options={'verbose_name': 'program'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
