# Generated by Django 2.2.9 on 2020-01-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0018_auto_20200126_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
