# Generated by Django 2.2.9 on 2020-01-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url_to_map', models.URLField(help_text='URL adresa na Google Mapy alebo obdobnú službu', verbose_name='URL k mape')),
            ],
            options={
                'verbose_name': 'poloha',
                'verbose_name_plural': 'polohy',
            },
        ),
    ]
