# Generated by Django 2.2.9 on 2020-01-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='subtitle',
            new_name='short_overview',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Location', verbose_name='poloha'),
        ),
    ]
