# Generated by Django 2.2.9 on 2020-01-26 17:57

from django.db import migrations, models
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200126_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dátum a čas'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_overview',
            field=models.CharField(blank=True, help_text='Zobrazuje sa na stránke s programom', max_length=100, verbose_name='krátky popis'),
        ),
    ]
