# Generated by Django 2.2.9 on 2020-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200126_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text="Podporuje Youtube, Vimeo a <a href='https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/oembed_providers.py'>dalšie stránky</a>", null=True),
        ),
    ]
