# Generated by Django 2.2.9 on 2020-01-26 18:59

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200126_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='speakers', to='home.Speaker', verbose_name='rečník'),
        ),
    ]
