# Generated by Django 2.2.9 on 2020-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20200126_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIllustration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'ilustrácia',
                'verbose_name_plural': 'ilustrácie',
            },
        ),
    ]
