# Generated by Django 2.2.9 on 2020-01-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_eventillustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventillustration',
            name='title',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
