# Generated by Django 2.2.9 on 2020-01-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0033_event_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllustrationImage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wagtailimages.image',),
        ),
        migrations.RemoveField(
            model_name='event',
            name='illustration',
        ),
        migrations.DeleteModel(
            name='Illustration',
        ),
    ]
