# Generated by Django 2.2.9 on 2020-01-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20200127_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='logo',
        ),
    ]
