# Generated by Django 2.2.9 on 2020-01-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_event_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ForeignKey(blank=True, limit_choices_to={'tags__name': 'illustration'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.IllustrationImage'),
        ),
    ]
