# Generated by Django 2.2.9 on 2020-01-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0037_auto_20200127_2222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IllustrationImage',
        ),
        migrations.RemoveField(
            model_name='event',
            name='logo',
        ),
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
