# Generated by Django 2.2.9 on 2020-01-31 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0038_auto_20200131_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='fotka'),
        ),
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='ikona'),
        ),
    ]
