# Generated by Django 2.2.9 on 2020-01-31 09:38

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20200131_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='meno'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='priezvisko'),
        ),
    ]
