# Generated by Django 2.2.9 on 2020-02-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20200131_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakerindexpage',
            options={'verbose_name': 'rečníci'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FF0000', max_length=20, verbose_name='farba'),
            preserve_default=False,
        ),
    ]
