# Generated by Django 3.0.4 on 2020-03-21 16:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_crowdfundingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalpage',
            name='hero_buttons',
            field=wagtail.core.fields.StreamField([('hero_buttons', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.URLBlock())]))], blank=True, help_text='Len prvé 2 tlacidla budú použité', null=True),
        ),
    ]
