# Generated by Django 2.2.9 on 2020-02-07 12:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0043_auto_20200207_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'program',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='eventindexpage',
            options={'verbose_name': 'archív'},
        ),
    ]
